<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PokedexSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('pokedex')->insert([
        	[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 255,
				'name' => 'Torchic',
				'type1' => 'Fire',
				'type2' => '',
				'HP' => 45,
				'attack' => 60,
				'defence' => 40,
				'sp_attack' => 70, 
				'sp_defence' => 50,
				'speed' => 45,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 256,
				'name' => 'Combusken',
				'type1' => 'Fire',
				'type2' => 'Fighting',
				'HP' => 60,
				'attack' => 85,
				'defence' => 60,
				'sp_attack' => 85, 
				'sp_defence' => 60,
				'speed' => 55,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 257,
				'name' => 'Blaziken',
				'type1' => 'Fire',
				'type2' => 'Fighting',
				'HP' => 80,
				'attack' => 120,
				'defence' => 70,
				'sp_attack' => 110, 
				'sp_defence' => 70,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 258,
				'name' => 'Mudkip',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 50,
				'attack' => 70,
				'defence' => 50,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 259,
				'name' => 'Marshtomp',
				'type1' => 'Water',
				'type2' => 'Ground',
				'HP' => 70,
				'attack' => 85,
				'defence' => 70,
				'sp_attack' => 60, 
				'sp_defence' => 70,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 260,
				'name' => 'Swampert',
				'type1' => 'Water',
				'type2' => 'Ground',
				'HP' => 100,
				'attack' => 110,
				'defence' => 90,
				'sp_attack' => 85, 
				'sp_defence' => 90,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 261,
				'name' => 'Poochyena',
				'type1' => 'Dark',
				'type2' => '',
				'HP' => 35,
				'attack' => 55,
				'defence' => 35,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 35,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 262,
				'name' => 'Mightyena',
				'type1' => 'Dark',
				'type2' => '',
				'HP' => 70,
				'attack' => 90,
				'defence' => 70,
				'sp_attack' => 60, 
				'sp_defence' => 60,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 263,
				'name' => 'Zigzagoon',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 38,
				'attack' => 30,
				'defence' => 41,
				'sp_attack' => 30, 
				'sp_defence' => 41,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 264,
				'name' => 'Linoone',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 78,
				'attack' => 70,
				'defence' => 61,
				'sp_attack' => 50, 
				'sp_defence' => 61,
				'speed' => 100,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 265,
				'name' => 'Wurmple',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 45,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 20, 
				'sp_defence' => 30,
				'speed' => 20,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 266,
				'name' => 'Silcoon',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 50,
				'attack' => 35,
				'defence' => 55,
				'sp_attack' => 25, 
				'sp_defence' => 25,
				'speed' => 15,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 267,
				'name' => 'Beautifly',
				'type1' => 'Bug',
				'type2' => 'Flying',
				'HP' => 60,
				'attack' => 70,
				'defence' => 50,
				'sp_attack' => 100, 
				'sp_defence' => 50,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 268,
				'name' => 'Cascoon',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 50,
				'attack' => 35,
				'defence' => 55,
				'sp_attack' => 25, 
				'sp_defence' => 25,
				'speed' => 15,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 269,
				'name' => 'Dustox',
				'type1' => 'Bug',
				'type2' => 'Poison',
				'HP' => 60,
				'attack' => 50,
				'defence' => 70,
				'sp_attack' => 50, 
				'sp_defence' => 90,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 270,
				'name' => 'Lotad',
				'type1' => 'Water',
				'type2' => 'Grass',
				'HP' => 40,
				'attack' => 30,
				'defence' => 30,
				'sp_attack' => 40, 
				'sp_defence' => 50,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 271,
				'name' => 'Lombre',
				'type1' => 'Water',
				'type2' => 'Grass',
				'HP' => 60,
				'attack' => 50,
				'defence' => 50,
				'sp_attack' => 60, 
				'sp_defence' => 70,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 272,
				'name' => 'Ludicolo',
				'type1' => 'Water',
				'type2' => 'Grass',
				'HP' => 80,
				'attack' => 70,
				'defence' => 70,
				'sp_attack' => 90, 
				'sp_defence' => 100,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 273,
				'name' => 'Seedot',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 40,
				'defence' => 50,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 274,
				'name' => 'Nuzleaf',
				'type1' => 'Grass',
				'type2' => 'Dark',
				'HP' => 70,
				'attack' => 70,
				'defence' => 40,
				'sp_attack' => 60, 
				'sp_defence' => 40,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 275,
				'name' => 'Shiftry',
				'type1' => 'Grass',
				'type2' => 'Dark',
				'HP' => 90,
				'attack' => 100,
				'defence' => 60,
				'sp_attack' => 90, 
				'sp_defence' => 60,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 276,
				'name' => 'Taillow',
				'type1' => 'Normal',
				'type2' => 'Flying',
				'HP' => 40,
				'attack' => 55,
				'defence' => 30,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 85,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 277,
				'name' => 'Swellow',
				'type1' => 'Normal',
				'type2' => 'Flying',
				'HP' => 60,
				'attack' => 85,
				'defence' => 60,
				'sp_attack' => 75, 
				'sp_defence' => 50,
				'speed' => 125,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 278,
				'name' => 'Wingull',
				'type1' => 'Water',
				'type2' => 'Flying',
				'HP' => 40,
				'attack' => 30,
				'defence' => 30,
				'sp_attack' => 55, 
				'sp_defence' => 30,
				'speed' => 85,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 279,
				'name' => 'Pelipper',
				'type1' => 'Water',
				'type2' => 'Flying',
				'HP' => 60,
				'attack' => 50,
				'defence' => 100,
				'sp_attack' => 95, 
				'sp_defence' => 70,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 280,
				'name' => 'Ralts',
				'type1' => 'Psychic',
				'type2' => 'Fairy',
				'HP' => 28,
				'attack' => 25,
				'defence' => 25,
				'sp_attack' => 45, 
				'sp_defence' => 35,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 281,
				'name' => 'Kirlia',
				'type1' => 'Psychic',
				'type2' => 'Fairy',
				'HP' => 38,
				'attack' => 35,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 282,
				'name' => 'Gardevoir',
				'type1' => 'Psychic',
				'type2' => 'Fairy',
				'HP' => 68,
				'attack' => 65,
				'defence' => 65,
				'sp_attack' => 125, 
				'sp_defence' => 115,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 283,
				'name' => 'Surskit',
				'type1' => 'Bug',
				'type2' => 'Water',
				'HP' => 40,
				'attack' => 30,
				'defence' => 32,
				'sp_attack' => 50, 
				'sp_defence' => 52,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 284,
				'name' => 'Masquerain',
				'type1' => 'Bug',
				'type2' => 'Flying',
				'HP' => 70,
				'attack' => 60,
				'defence' => 62,
				'sp_attack' => 100, 
				'sp_defence' => 82,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 285,
				'name' => 'Shroomish',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 60,
				'attack' => 40,
				'defence' => 60,
				'sp_attack' => 40, 
				'sp_defence' => 60,
				'speed' => 35,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 286,
				'name' => 'Breloom',
				'type1' => 'Grass',
				'type2' => 'Fighting',
				'HP' => 60,
				'attack' => 130,
				'defence' => 80,
				'sp_attack' => 60, 
				'sp_defence' => 60,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 287,
				'name' => 'Slakoth',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 60,
				'attack' => 60,
				'defence' => 60,
				'sp_attack' => 35, 
				'sp_defence' => 35,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 288,
				'name' => 'Vigoroth',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 80,
				'attack' => 80,
				'defence' => 80,
				'sp_attack' => 55, 
				'sp_defence' => 55,
				'speed' => 90,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 289,
				'name' => 'Slaking',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 150,
				'attack' => 160,
				'defence' => 100,
				'sp_attack' => 95, 
				'sp_defence' => 65,
				'speed' => 100,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 290,
				'name' => 'Nincada',
				'type1' => 'Bug',
				'type2' => 'Ground',
				'HP' => 31,
				'attack' => 45,
				'defence' => 90,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 291,
				'name' => 'Ninjask',
				'type1' => 'Bug',
				'type2' => 'Flying',
				'HP' => 61,
				'attack' => 90,
				'defence' => 45,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 160,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 292,
				'name' => 'Shedinja',
				'type1' => 'Bug',
				'type2' => 'Ghost',
				'HP' => 1,
				'attack' => 90,
				'defence' => 45,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 293,
				'name' => 'Whismur',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 64,
				'attack' => 51,
				'defence' => 23,
				'sp_attack' => 51, 
				'sp_defence' => 23,
				'speed' => 28,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 294,
				'name' => 'Loudred',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 84,
				'attack' => 71,
				'defence' => 43,
				'sp_attack' => 71, 
				'sp_defence' => 43,
				'speed' => 48,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 295,
				'name' => 'Exploud',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 104,
				'attack' => 91,
				'defence' => 63,
				'sp_attack' => 91, 
				'sp_defence' => 73,
				'speed' => 68,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			
		]);
    }
}
