<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class PokedexSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('pokedex')->insert([
        	[
				'id' => 252,
				'name' => 'Treecko',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 253,
				'name' => 'Grovyle',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 65,
				'defence' => 45,
				'sp_attack' => 85, 
				'sp_defence' => 65,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 254,
				'name' => 'Sceptile',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 65,
				'sp_attack' => 105, 
				'sp_defence' => 85,
				'speed' => 120,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 255,
				'name' => 'Torchic',
				'type1' => 'Fire',
				'type2' => '',
				'HP' => 45,
				'attack' => 60,
				'defence' => 40,
				'sp_attack' => 70, 
				'sp_defence' => 50,
				'speed' => 45,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 256,
				'name' => 'Combusken',
				'type1' => 'Fire',
				'type2' => 'Fighting',
				'HP' => 60,
				'attack' => 85,
				'defence' => 60,
				'sp_attack' => 85, 
				'sp_defence' => 60,
				'speed' => 55,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 257,
				'name' => 'Blaziken',
				'type1' => 'Fire',
				'type2' => 'Fighting',
				'HP' => 80,
				'attack' => 120,
				'defence' => 70,
				'sp_attack' => 110, 
				'sp_defence' => 70,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 258,
				'name' => 'Mudkip',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 50,
				'attack' => 70,
				'defence' => 50,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 259,
				'name' => 'Marshtomp',
				'type1' => 'Water',
				'type2' => 'Ground',
				'HP' => 70,
				'attack' => 85,
				'defence' => 70,
				'sp_attack' => 60, 
				'sp_defence' => 70,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 260,
				'name' => 'Swampert',
				'type1' => 'Water',
				'type2' => 'Ground',
				'HP' => 100,
				'attack' => 110,
				'defence' => 90,
				'sp_attack' => 85, 
				'sp_defence' => 90,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 261,
				'name' => 'Poochyena',
				'type1' => 'Dark',
				'type2' => '',
				'HP' => 35,
				'attack' => 55,
				'defence' => 35,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 35,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 262,
				'name' => 'Mightyena',
				'type1' => 'Dark',
				'type2' => '',
				'HP' => 70,
				'attack' => 90,
				'defence' => 70,
				'sp_attack' => 60, 
				'sp_defence' => 60,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 263,
				'name' => 'Zigzagoon',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 38,
				'attack' => 30,
				'defence' => 41,
				'sp_attack' => 30, 
				'sp_defence' => 41,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 264,
				'name' => 'Linoone',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 78,
				'attack' => 70,
				'defence' => 61,
				'sp_attack' => 50, 
				'sp_defence' => 61,
				'speed' => 100,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 265,
				'name' => 'Wurmple',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 45,
				'attack' => 45,
				'defence' => 35,
				'sp_attack' => 20, 
				'sp_defence' => 30,
				'speed' => 20,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 266,
				'name' => 'Silcoon',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 50,
				'attack' => 35,
				'defence' => 55,
				'sp_attack' => 25, 
				'sp_defence' => 25,
				'speed' => 15,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 267,
				'name' => 'Beautifly',
				'type1' => 'Bug',
				'type2' => 'Flying',
				'HP' => 60,
				'attack' => 70,
				'defence' => 50,
				'sp_attack' => 100, 
				'sp_defence' => 50,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 268,
				'name' => 'Cascoon',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 50,
				'attack' => 35,
				'defence' => 55,
				'sp_attack' => 25, 
				'sp_defence' => 25,
				'speed' => 15,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 269,
				'name' => 'Dustox',
				'type1' => 'Bug',
				'type2' => 'Poison',
				'HP' => 60,
				'attack' => 50,
				'defence' => 70,
				'sp_attack' => 50, 
				'sp_defence' => 90,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 270,
				'name' => 'Lotad',
				'type1' => 'Water',
				'type2' => 'Grass',
				'HP' => 40,
				'attack' => 30,
				'defence' => 30,
				'sp_attack' => 40, 
				'sp_defence' => 50,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 271,
				'name' => 'Lombre',
				'type1' => 'Water',
				'type2' => 'Grass',
				'HP' => 60,
				'attack' => 50,
				'defence' => 50,
				'sp_attack' => 60, 
				'sp_defence' => 70,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 272,
				'name' => 'Ludicolo',
				'type1' => 'Water',
				'type2' => 'Grass',
				'HP' => 80,
				'attack' => 70,
				'defence' => 70,
				'sp_attack' => 90, 
				'sp_defence' => 100,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 273,
				'name' => 'Seedot',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 40,
				'attack' => 40,
				'defence' => 50,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 274,
				'name' => 'Nuzleaf',
				'type1' => 'Grass',
				'type2' => 'Dark',
				'HP' => 70,
				'attack' => 70,
				'defence' => 40,
				'sp_attack' => 60, 
				'sp_defence' => 40,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 275,
				'name' => 'Shiftry',
				'type1' => 'Grass',
				'type2' => 'Dark',
				'HP' => 90,
				'attack' => 100,
				'defence' => 60,
				'sp_attack' => 90, 
				'sp_defence' => 60,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 276,
				'name' => 'Taillow',
				'type1' => 'Normal',
				'type2' => 'Flying',
				'HP' => 40,
				'attack' => 55,
				'defence' => 30,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 85,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 277,
				'name' => 'Swellow',
				'type1' => 'Normal',
				'type2' => 'Flying',
				'HP' => 60,
				'attack' => 85,
				'defence' => 60,
				'sp_attack' => 75, 
				'sp_defence' => 50,
				'speed' => 125,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 278,
				'name' => 'Wingull',
				'type1' => 'Water',
				'type2' => 'Flying',
				'HP' => 40,
				'attack' => 30,
				'defence' => 30,
				'sp_attack' => 55, 
				'sp_defence' => 30,
				'speed' => 85,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 279,
				'name' => 'Pelipper',
				'type1' => 'Water',
				'type2' => 'Flying',
				'HP' => 60,
				'attack' => 50,
				'defence' => 100,
				'sp_attack' => 95, 
				'sp_defence' => 70,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 280,
				'name' => 'Ralts',
				'type1' => 'Psychic',
				'type2' => 'Fairy',
				'HP' => 28,
				'attack' => 25,
				'defence' => 25,
				'sp_attack' => 45, 
				'sp_defence' => 35,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 281,
				'name' => 'Kirlia',
				'type1' => 'Psychic',
				'type2' => 'Fairy',
				'HP' => 38,
				'attack' => 35,
				'defence' => 35,
				'sp_attack' => 65, 
				'sp_defence' => 55,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 282,
				'name' => 'Gardevoir',
				'type1' => 'Psychic',
				'type2' => 'Fairy',
				'HP' => 68,
				'attack' => 65,
				'defence' => 65,
				'sp_attack' => 125, 
				'sp_defence' => 115,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 283,
				'name' => 'Surskit',
				'type1' => 'Bug',
				'type2' => 'Water',
				'HP' => 40,
				'attack' => 30,
				'defence' => 32,
				'sp_attack' => 50, 
				'sp_defence' => 52,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 284,
				'name' => 'Masquerain',
				'type1' => 'Bug',
				'type2' => 'Flying',
				'HP' => 70,
				'attack' => 60,
				'defence' => 62,
				'sp_attack' => 100, 
				'sp_defence' => 82,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 285,
				'name' => 'Shroomish',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 60,
				'attack' => 40,
				'defence' => 60,
				'sp_attack' => 40, 
				'sp_defence' => 60,
				'speed' => 35,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 286,
				'name' => 'Breloom',
				'type1' => 'Grass',
				'type2' => 'Fighting',
				'HP' => 60,
				'attack' => 130,
				'defence' => 80,
				'sp_attack' => 60, 
				'sp_defence' => 60,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 287,
				'name' => 'Slakoth',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 60,
				'attack' => 60,
				'defence' => 60,
				'sp_attack' => 35, 
				'sp_defence' => 35,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 288,
				'name' => 'Vigoroth',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 80,
				'attack' => 80,
				'defence' => 80,
				'sp_attack' => 55, 
				'sp_defence' => 55,
				'speed' => 90,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 289,
				'name' => 'Slaking',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 150,
				'attack' => 160,
				'defence' => 100,
				'sp_attack' => 95, 
				'sp_defence' => 65,
				'speed' => 100,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 290,
				'name' => 'Nincada',
				'type1' => 'Bug',
				'type2' => 'Ground',
				'HP' => 31,
				'attack' => 45,
				'defence' => 90,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 291,
				'name' => 'Ninjask',
				'type1' => 'Bug',
				'type2' => 'Flying',
				'HP' => 61,
				'attack' => 90,
				'defence' => 45,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 160,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 292,
				'name' => 'Shedinja',
				'type1' => 'Bug',
				'type2' => 'Ghost',
				'HP' => 1,
				'attack' => 90,
				'defence' => 45,
				'sp_attack' => 30, 
				'sp_defence' => 30,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 293,
				'name' => 'Whismur',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 64,
				'attack' => 51,
				'defence' => 23,
				'sp_attack' => 51, 
				'sp_defence' => 23,
				'speed' => 28,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 294,
				'name' => 'Loudred',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 84,
				'attack' => 71,
				'defence' => 43,
				'sp_attack' => 71, 
				'sp_defence' => 43,
				'speed' => 48,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 295,
				'name' => 'Exploud',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 104,
				'attack' => 91,
				'defence' => 63,
				'sp_attack' => 91, 
				'sp_defence' => 73,
				'speed' => 68,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 296,
				'name' => 'Makuhita',
				'type1' => 'Fighting',
				'type2' => '',
				'HP' => 72,
				'attack' => 60,
				'defence' => 30,
				'sp_attack' => 20, 
				'sp_defence' => 30,
				'speed' => 25,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 297,
				'name' => 'Hariyama',
				'type1' => 'Fighting',
				'type2' => '',
				'HP' => 144,
				'attack' => 120,
				'defence' => 60,
				'sp_attack' => 40, 
				'sp_defence' => 60,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 298,
				'name' => 'Azurill',
				'type1' => 'Normal',
				'type2' => 'Fairy',
				'HP' => 50,
				'attack' => 20,
				'defence' => 40,
				'sp_attack' => 20, 
				'sp_defence' => 40,
				'speed' => 20,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 299,
				'name' => 'Nosepass',
				'type1' => 'Rock',
				'type2' => '',
				'HP' => 30,
				'attack' => 45,
				'defence' => 135,
				'sp_attack' => 45, 
				'sp_defence' => 90,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 300,
				'name' => 'Skitty',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 50,
				'attack' => 45,
				'defence' => 45,
				'sp_attack' => 35, 
				'sp_defence' => 35,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 301,
				'name' => 'Delcatty',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 70,
				'attack' => 65,
				'defence' => 65,
				'sp_attack' => 55, 
				'sp_defence' => 55,
				'speed' => 90,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 302,
				'name' => 'Sableye',
				'type1' => 'Dark',
				'type2' => 'Ghost',
				'HP' => 50,
				'attack' => 75,
				'defence' => 75,
				'sp_attack' => 65, 
				'sp_defence' => 65,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 303,
				'name' => 'Mawile',
				'type1' => 'Steel',
				'type2' => 'Fairy',
				'HP' => 50,
				'attack' => 85,
				'defence' => 85,
				'sp_attack' => 55, 
				'sp_defence' => 55,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 304,
				'name' => 'Aron',
				'type1' => 'Steel',
				'type2' => 'Rock',
				'HP' => 50,
				'attack' => 70,
				'defence' => 100,
				'sp_attack' => 40, 
				'sp_defence' => 40,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 305,
				'name' => 'Lairon',
				'type1' => 'Steel',
				'type2' => 'Rock',
				'HP' => 60,
				'attack' => 90,
				'defence' => 140,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 306,
				'name' => 'Aggron',
				'type1' => 'Steel',
				'type2' => 'Ground',
				'HP' => 70,
				'attack' => 110,
				'defence' => 180,
				'sp_attack' => 60, 
				'sp_defence' => 60,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 307,
				'name' => 'Meditite',
				'type1' => 'Fighting',
				'type2' => 'Psychic',
				'HP' => 30,
				'attack' => 40,
				'defence' => 55,
				'sp_attack' => 40, 
				'sp_defence' => 55,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 308,
				'name' => 'Medicham',
				'type1' => 'Fighting',
				'type2' => 'Psychic',
				'HP' => 60,
				'attack' => 60,
				'defence' => 75,
				'sp_attack' => 60, 
				'sp_defence' => 75,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 309,
				'name' => 'Electrike',
				'type1' => 'Electric',
				'type2' => '',
				'HP' => 40,
				'attack' => 45,
				'defence' => 40,
				'sp_attack' => 65, 
				'sp_defence' => 40,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 310,
				'name' => 'Manectric',
				'type1' => 'Electric',
				'type2' => '',
				'HP' => 70,
				'attack' => 75,
				'defence' => 60,
				'sp_attack' => 105, 
				'sp_defence' => 60,
				'speed' => 105,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 311,
				'name' => 'Plulse',
				'type1' => 'Electric',
				'type2' => '',
				'HP' => 60,
				'attack' => 50,
				'defence' => 40,
				'sp_attack' => 85, 
				'sp_defence' => 75,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 312,
				'name' => 'Minun',
				'type1' => 'Electric',
				'type2' => '',
				'HP' => 60,
				'attack' => 40,
				'defence' => 50,
				'sp_attack' => 75, 
				'sp_defence' => 85,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 313,
				'name' => 'Volbeat',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 65,
				'attack' => 73,
				'defence' => 75,
				'sp_attack' => 7, 
				'sp_defence' => 85,
				'speed' => 85,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 314,
				'name' => 'Illumise',
				'type1' => 'Bug',
				'type2' => '',
				'HP' => 65,
				'attack' => 47,
				'defence' => 75,
				'sp_attack' => 73, 
				'sp_defence' => 85,
				'speed' => 85,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 315,
				'name' => 'Roselia',
				'type1' => 'Grass',
				'type2' => 'Poison',
				'HP' => 50,
				'attack' => 60,
				'defence' => 45,
				'sp_attack' => 100, 
				'sp_defence' => 80,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 316,
				'name' => 'Gulpin',
				'type1' => 'Poison',
				'type2' => '',
				'HP' => 70,
				'attack' => 43,
				'defence' => 53,
				'sp_attack' => 43, 
				'sp_defence' => 53,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 317,
				'name' => 'Swalot',
				'type1' => 'Poison',
				'type2' => '',
				'HP' => 100,
				'attack' => 73,
				'defence' => 83,
				'sp_attack' => 73, 
				'sp_defence' => 83,
				'speed' => 55,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 318,
				'name' => 'Carvanha',
				'type1' => 'Water',
				'type2' => 'Dark',
				'HP' => 45,
				'attack' => 90,
				'defence' => 20,
				'sp_attack' => 65, 
				'sp_defence' => 20,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 319,
				'name' => 'Sharpedo',
				'type1' => 'Water',
				'type2' => 'Dark',
				'HP' => 70,
				'attack' => 120,
				'defence' => 40,
				'sp_attack' => 95, 
				'sp_defence' => 40,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 320,
				'name' => 'Wailmer',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 130,
				'attack' => 70,
				'defence' => 35,
				'sp_attack' => 70, 
				'sp_defence' => 35,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 321,
				'name' => 'Wailord',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 170,
				'attack' => 90,
				'defence' => 45,
				'sp_attack' => 90, 
				'sp_defence' => 45,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 322,
				'name' => 'Numel',
				'type1' => 'Fire',
				'type2' => 'Ground',
				'HP' => 60,
				'attack' => 60,
				'defence' => 40,
				'sp_attack' => 65, 
				'sp_defence' => 45,
				'speed' => 35,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 323,
				'name' => 'Camerupt',
				'type1' => 'Fire',
				'type2' => 'Ground',
				'HP' => 70,
				'attack' => 100,
				'defence' => 70,
				'sp_attack' => 105, 
				'sp_defence' => 75,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 324,
				'name' => 'Torkoal',
				'type1' => 'Fire',
				'type2' => '',
				'HP' => 70,
				'attack' => 85,
				'defence' => 140,
				'sp_attack' => 85, 
				'sp_defence' => 70,
				'speed' => 20,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 325,
				'name' => 'Spoink',
				'type1' => 'Psychic',
				'type2' => '',
				'HP' => 60,
				'attack' => 25,
				'defence' => 35,
				'sp_attack' => 70, 
				'sp_defence' => 80,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 326,
				'name' => 'Grumpig',
				'type1' => 'Psychic',
				'type2' => '',
				'HP' => 80,
				'attack' => 45,
				'defence' => 65,
				'sp_attack' => 90, 
				'sp_defence' => 110,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 327,
				'name' => 'Spinda',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 60,
				'attack' => 60,
				'defence' => 60,
				'sp_attack' => 60, 
				'sp_defence' => 60,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 328,
				'name' => 'Trapinch',
				'type1' => 'Ground',
				'type2' => '',
				'HP' => 45,
				'attack' => 100,
				'defence' => 45,
				'sp_attack' => 45, 
				'sp_defence' => 45,
				'speed' => 10,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 329,
				'name' => 'Vibrava',
				'type1' => 'Ground',
				'type2' => 'Dragon',
				'HP' => 50,
				'attack' => 70,
				'defence' => 50,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 330,
				'name' => 'Flygon',
				'type1' => 'Ground',
				'type2' => 'Dragon',
				'HP' => 80,
				'attack' => 100,
				'defence' => 80,
				'sp_attack' => 80, 
				'sp_defence' => 80,
				'speed' => 100,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 331,
				'name' => 'Canea',
				'type1' => 'Grass',
				'type2' => '',
				'HP' => 50,
				'attack' => 85,
				'defence' => 40,
				'sp_attack' => 85, 
				'sp_defence' => 40,
				'speed' => 35,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 332,
				'name' => 'Cacturne',
				'type1' => 'Grass',
				'type2' => 'Dark',
				'HP' => 70,
				'attack' => 115,
				'defence' => 60,
				'sp_attack' => 115, 
				'sp_defence' => 60,
				'speed' => 55,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 333,
				'name' => 'Swablu',
				'type1' => 'Normal',
				'type2' => 'Flying',
				'HP' => 45,
				'attack' => 40,
				'defence' => 60,
				'sp_attack' => 40, 
				'sp_defence' => 75,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 334,
				'name' => 'Altaria',
				'type1' => 'Dragon',
				'type2' => 'Flying',
				'HP' => 75,
				'attack' => 70,
				'defence' => 90,
				'sp_attack' => 70, 
				'sp_defence' => 105,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 335,
				'name' => 'Zangoose',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 73,
				'attack' => 115,
				'defence' => 60,
				'sp_attack' => 60, 
				'sp_defence' => 60,
				'speed' => 90,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 336,
				'name' => 'Seviper',
				'type1' => 'Poison',
				'type2' => '',
				'HP' => 73,
				'attack' => 100,
				'defence' => 60,
				'sp_attack' => 100, 
				'sp_defence' => 60,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 337,
				'name' => 'Lunatone',
				'type1' => 'Rock',
				'type2' => 'Psychic',
				'HP' => 90,
				'attack' => 55,
				'defence' => 65,
				'sp_attack' => 95, 
				'sp_defence' => 85,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 338,
				'name' => 'Solrock',
				'type1' => 'Rock',
				'type2' => 'Psychic',
				'HP' => 90,
				'attack' => 95,
				'defence' => 85,
				'sp_attack' => 55, 
				'sp_defence' => 65,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 339,
				'name' => 'Barboach',
				'type1' => 'Water',
				'type2' => 'Ground',
				'HP' => 50,
				'attack' => 48,
				'defence' => 43,
				'sp_attack' => 46, 
				'sp_defence' => 41,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 340,
				'name' => 'Whiscash',
				'type1' => 'Water',
				'type2' => 'Ground',
				'HP' => 110,
				'attack' => 78,
				'defence' => 73,
				'sp_attack' => 76, 
				'sp_defence' => 71,
				'speed' => 60,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 341,
				'name' => 'Corphish',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 43,
				'attack' => 80,
				'defence' => 65,
				'sp_attack' => 50, 
				'sp_defence' => 35,
				'speed' => 35,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 342,
				'name' => 'Crawdaunt',
				'type1' => 'Water',
				'type2' => 'Dark',
				'HP' => 63,
				'attack' => 120,
				'defence' => 85,
				'sp_attack' => 90, 
				'sp_defence' => 55,
				'speed' => 55,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 343,
				'name' => 'Baltoy',
				'type1' => 'Ground',
				'type2' => 'Psychic',
				'HP' => 40,
				'attack' => 40,
				'defence' => 55,
				'sp_attack' => 40, 
				'sp_defence' => 70,
				'speed' => 55,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 344,
				'name' => 'Claydol',
				'type1' => 'Ground',
				'type2' => 'Psychic',
				'HP' => 60,
				'attack' => 70,
				'defence' => 105,
				'sp_attack' => 70, 
				'sp_defence' => 120,
				'speed' => 75,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 345,
				'name' => 'Lileep',
				'type1' => 'Rock',
				'type2' => 'Grass',
				'HP' => 66,
				'attack' => 41,
				'defence' => 77,
				'sp_attack' => 61, 
				'sp_defence' => 87,
				'speed' => 23,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 346,
				'name' => 'Cradily',
				'type1' => 'Rock',
				'type2' => 'Grass',
				'HP' => 86,
				'attack' => 81,
				'defence' => 97,
				'sp_attack' => 81, 
				'sp_defence' => 107,
				'speed' => 43,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 347,
				'name' => 'Anorith',
				'type1' => 'Rock',
				'type2' => 'Bug',
				'HP' => 45,
				'attack' => 95,
				'defence' => 50,
				'sp_attack' => 40, 
				'sp_defence' => 50,
				'speed' => 75,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 348,
				'name' => 'Armaldo',
				'type1' => 'Rock',
				'type2' => 'Bug',
				'HP' => 75,
				'attack' => 125,
				'defence' => 100,
				'sp_attack' => 70, 
				'sp_defence' => 80,
				'speed' => 45,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 349,
				'name' => 'Feebas',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 20,
				'attack' => 15,
				'defence' => 20,
				'sp_attack' => 10, 
				'sp_defence' => 55,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 350,
				'name' => 'Milotic',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 95,
				'attack' => 60,
				'defence' => 79,
				'sp_attack' => 100, 
				'sp_defence' => 125,
				'speed' => 81,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 351,
				'name' => 'Castform',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 70,
				'attack' => 70,
				'defence' => 70,
				'sp_attack' => 70, 
				'sp_defence' => 70,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 352,
				'name' => 'Kecleon',
				'type1' => 'Normal',
				'type2' => '',
				'HP' => 60,
				'attack' => 90,
				'defence' => 70,
				'sp_attack' => 60, 
				'sp_defence' => 120,
				'speed' => 40,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 353,
				'name' => 'Shuppet',
				'type1' => 'Ghost',
				'type2' => '',
				'HP' => 44,
				'attack' => 75,
				'defence' => 35,
				'sp_attack' => 63, 
				'sp_defence' => 33,
				'speed' => 45,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 354,
				'name' => 'Banette',
				'type1' => 'Ghost',
				'type2' => '',
				'HP' => 64,
				'attack' => 115,
				'defence' => 65,
				'sp_attack' => 83, 
				'sp_defence' => 63,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 355,
				'name' => 'Duskull',
				'type1' => 'Ghost',
				'type2' => '',
				'HP' => 20,
				'attack' => 40,
				'defence' => 90,
				'sp_attack' => 30, 
				'sp_defence' => 90,
				'speed' => 25,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 356,
				'name' => 'Dusclops',
				'type1' => 'Ghost',
				'type2' => '',
				'HP' => 40,
				'attack' => 70,
				'defence' => 130,
				'sp_attack' => 60, 
				'sp_defence' => 130,
				'speed' => 25,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 357,
				'name' => 'Tropius',
				'type1' => 'Grass',
				'type2' => 'Flying',
				'HP' => 99,
				'attack' => 68,
				'defence' => 83,
				'sp_attack' => 72, 
				'sp_defence' => 87,
				'speed' => 51,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 358,
				'name' => 'Chimecho',
				'type1' => 'Psychic',
				'type2' => '',
				'HP' => 75,
				'attack' => 50,
				'defence' => 80,
				'sp_attack' => 95, 
				'sp_defence' => 90,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 359,
				'name' => 'Absol',
				'type1' => 'Dark',
				'type2' => '',
				'HP' => 65,
				'attack' => 130,
				'defence' => 60,
				'sp_attack' => 75, 
				'sp_defence' => 60,
				'speed' => 75,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 360,
				'name' => 'Wynaut',
				'type1' => 'Psychic',
				'type2' => '',
				'HP' => 95,
				'attack' => 23,
				'defence' => 48,
				'sp_attack' => 23, 
				'sp_defence' => 48,
				'speed' => 23,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 361,
				'name' => 'Snorunt',
				'type1' => 'Ice',
				'type2' => '',
				'HP' => 50,
				'attack' => 50,
				'defence' => 50,
				'sp_attack' => 50, 
				'sp_defence' => 50,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 362,
				'name' => 'Glalie',
				'type1' => 'Ice',
				'type2' => '',
				'HP' => 80,
				'attack' => 80,
				'defence' => 80,
				'sp_attack' => 80, 
				'sp_defence' => 80,
				'speed' => 80,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 363,
				'name' => 'Spheal',
				'type1' => 'Ice',
				'type2' => 'Water',
				'HP' => 70,
				'attack' => 40,
				'defence' => 50,
				'sp_attack' => 55, 
				'sp_defence' => 50,
				'speed' => 25,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 364,
				'name' => 'Sealeo',
				'type1' => 'Ice',
				'type2' => 'Water',
				'HP' => 90,
				'attack' => 60,
				'defence' => 70,
				'sp_attack' => 75, 
				'sp_defence' => 70,
				'speed' => 45,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 365,
				'name' => 'Walrein',
				'type1' => 'Ice',
				'type2' => 'Water',
				'HP' => 110,
				'attack' => 80,
				'defence' => 90,
				'sp_attack' => 95, 
				'sp_defence' => 90,
				'speed' => 65,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 366,
				'name' => 'Clamperi',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 35,
				'attack' => 64,
				'defence' => 85,
				'sp_attack' => 74, 
				'sp_defence' => 55,
				'speed' => 32,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 367,
				'name' => 'Huntail',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 55,
				'attack' => 104,
				'defence' => 105,
				'sp_attack' => 94, 
				'sp_defence' => 75,
				'speed' => 52,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 368,
				'name' => 'Gorebyss',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 55,
				'attack' => 84,
				'defence' => 105,
				'sp_attack' => 114, 
				'sp_defence' => 75,
				'speed' => 52,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 369,
				'name' => 'Relicanth',
				'type1' => 'Water',
				'type2' => 'Rock',
				'HP' => 100,
				'attack' => 90,
				'defence' => 130,
				'sp_attack' => 45, 
				'sp_defence' => 65,
				'speed' => 55,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 370,
				'name' => 'Luvdisc',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 43,
				'attack' => 30,
				'defence' => 55,
				'sp_attack' => 40, 
				'sp_defence' => 65,
				'speed' => 97,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 371,
				'name' => 'Bagon',
				'type1' => 'Dragon',
				'type2' => '',
				'HP' => 45,
				'attack' => 75,
				'defence' => 60,
				'sp_attack' => 40, 
				'sp_defence' => 30,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 372,
				'name' => 'Shelgon',
				'type1' => 'Dragon',
				'type2' => '',
				'HP' => 65,
				'attack' => 95,
				'defence' => 100,
				'sp_attack' => 60, 
				'sp_defence' => 50,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 373,
				'name' => 'Salamence',
				'type1' => 'Dragon',
				'type2' => 'Flying',
				'HP' => 95,
				'attack' => 135,
				'defence' => 80,
				'sp_attack' => 110, 
				'sp_defence' => 80,
				'speed' => 100,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 374,
				'name' => 'Beldum',
				'type1' => 'Steel',
				'type2' => 'Psychic',
				'HP' => 40,
				'attack' => 55,
				'defence' => 80,
				'sp_attack' => 35, 
				'sp_defence' => 60,
				'speed' => 30,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 375,
				'name' => 'Metang',
				'type1' => 'Steel',
				'type2' => 'Psychic',
				'HP' => 60,
				'attack' => 75,
				'defence' => 100,
				'sp_attack' => 55, 
				'sp_defence' => 80,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 376,
				'name' => 'Metagross',
				'type1' => 'Steel',
				'type2' => 'Psychic',
				'HP' => 80,
				'attack' => 135,
				'defence' => 130,
				'sp_attack' => 95, 
				'sp_defence' => 90,
				'speed' => 70,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 377,
				'name' => 'Regirock',
				'type1' => 'Rock',
				'type2' => '',
				'HP' => 80,
				'attack' => 100,
				'defence' => 200,
				'sp_attack' => 50, 
				'sp_defence' => 100,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 1,
			],
			[
				'id' => 378,
				'name' => 'Regice',
				'type1' => 'Ice',
				'type2' => '',
				'HP' => 80,
				'attack' => 50,
				'defence' => 100,
				'sp_attack' => 100, 
				'sp_defence' => 200,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 1,
			],
			[
				'id' => 379,
				'name' => 'Registeel',
				'type1' => 'Steel',
				'type2' => '',
				'HP' => 80,
				'attack' => 75,
				'defence' => 150,
				'sp_attack' => 75, 
				'sp_defence' => 150,
				'speed' => 50,
				'generation' => 3,
				'legendary' => 1,
			],
			[
				'id' => 380,
				'name' => 'Latias',
				'type1' => 'Dragon',
				'type2' => 'Psychic',
				'HP' => 80,
				'attack' => 80,
				'defence' => 90,
				'sp_attack' => 110, 
				'sp_defence' => 130,
				'speed' => 110,
				'generation' => 3,
				'legendary' => 1,
			],
			[
				'id' => 381,
				'name' => 'Latios',
				'type1' => 'Dragon',
				'type2' => 'Psychic',
				'HP' => 80,
				'attack' => 90,
				'defence' => 80,
				'sp_attack' => 130, 
				'sp_defence' => 110,
				'speed' => 110,
				'generation' => 3,
				'legendary' => 1,
			],
			[
				'id' => 382,
				'name' => 'Kyogre',
				'type1' => 'Water',
				'type2' => '',
				'HP' => 100,
				'attack' => 100,
				'defence' => 90,
				'sp_attack' => 150, 
				'sp_defence' => 140,
				'speed' => 90,
				'generation' => 3,
				'legendary' => 1,
			],
			[
				'id' => 383,
				'name' => 'Groudon',
				'type1' => 'Fire',
				'type2' => '',
				'HP' => 100,
				'attack' => 150,
				'defence' => 140,
				'sp_attack' => 100, 
				'sp_defence' => 90,
				'speed' => 90,
				'generation' => 3,
				'legendary' => 1,
			],
			[
				'id' => 384,
				'name' => 'Rayquaza',
				'type1' => 'Dragon',
				'type2' => 'Flying',
				'HP' => 105,
				'attack' => 150,
				'defence' => 90,
				'sp_attack' => 150, 
				'sp_defence' => 90,
				'speed' => 95,
				'generation' => 3,
				'legendary' => 1,
			],
			[
				'id' => 385,
				'name' => 'Jirachi',
				'type1' => 'Steel',
				'type2' => 'Psychic',
				'HP' => 100,
				'attack' => 100,
				'defence' => 100,
				'sp_attack' => 100, 
				'sp_defence' => 100,
				'speed' => 100,
				'generation' => 3,
				'legendary' => 0,
			],
			[
				'id' => 386,
				'name' => 'Deoxys',
				'type1' => 'Psychic',
				'type2' => '',
				'HP' => 50,
				'attack' => 150,
				'defence' => 50,
				'sp_attack' => 150, 
				'sp_defence' => 50,
				'speed' => 150,
				'generation' => 3,
				'legendary' => 0,
			],
		]);
    }
}
